# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Alvis-NLPPlatform
version:      0.3
version_from: lib/Alvis/NLPPlatform.pm
installdirs:  site
requires:
    Alvis::Pipeline:               0
    Alvis::TermTagger:             0.3
    Config::General:               2.3
    Data::Dumper:                  0
    Fcntl:                         0
    Getopt::Long:                  0
    IO::File:                      0
    IO::Socket:                    0
    IO::Socket::INET:              0
    Pod::Usage:                    0
    Sys::Hostname:                 0
    Time::HiRes:                   0
    utf8:                          0
    XML::LibXML:                   0
    XML::Parser::PerlSAX:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
